# -*- coding: utf-8 -*-
"""vector_embedding_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATIIQtZgZV8cLx08m4izPDN6UpRqVVQn
"""

!pip install --upgrade gensim

import gensim.downloader as api
model = api.load("word2vec-google-news-300")

word_vector = model

print(word_vector['Artificial'])

print(word_vector['dog'].shape)

print(word_vector.most_similar(positive = ['King', 'girl'] , negative= ['Man'], topn=10))

print(word_vector.most_similar(positive = ['Lion', 'Cow'] , negative= ['Prey'], topn=10))

print(word_vector.similarity('Lion', 'Pig'))
print(word_vector.similarity('man', 'woman'))
print(word_vector.similarity('orange', 'fruit'))

print(word_vector.most_similar("Mars", topn=5))

import numpy as np

word1 = "Mars"
word2 = "Jupiter"

word3 = "Grandparents"
word4 = "Son"

word5 = "Heaven"
word6 = "Hell"

#here is the differences of the vector
vec_diff1 = word_vector[word1] - word_vector[word2]
vec_diff2 = word_vector[word3] - word_vector[word4]
vec_diff3 = word_vector[word5] - word_vector[word6]

#now let's calculate the magnitude

mg_diff1 = np.linalg.norm(vec_diff1)
mg_diff2 = np.linalg.norm(vec_diff2)
mg_diff3 = np.linalg.norm(vec_diff3)

print ("between {} and {} magnitude is {:.2f}".format(word1, word2, mg_diff1))
print ("between {} and {} magnitude is {:.2f}".format(word3, word4, mg_diff2))
print ("between {} and {} magnitude is {:.2f}".format(word5, word6, mg_diff3))

"""### **Now we will code the embeddings and from this part will go to the real notebook**"""

import torch
input_ids = torch.tensor([2, 3, 5, 1])

vocab_size = 6
out_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, out_dim)

#all the weights initially given
print(embedding_layer.weight)

#lookup table- as if you specify the id_number you can see the vectors

print(embedding_layer(torch.tensor([3])))

print(embedding_layer(input_ids))

